"""Add surname in authors.

Revision ID: 668b8abb03f7
Revises: 468e83757dbe
Create Date: 2024-03-04 18:10:05.518007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668b8abb03f7'
down_revision = '468e83757dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
