"""Add column is_deleted in Authors.

Revision ID: 93676feae1e1
Revises: 668b8abb03f7
Create Date: 2024-03-04 19:38:10.374018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93676feae1e1'
down_revision = '668b8abb03f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
